### ISSUE TITLE
Show tracks on hover

### ISSUE THREAD

**Issue by eltongonc** [nghiepit/smooth-scrollbar-react#15]
Hi, thank you for this!

Is there a way to show the tracks when you hover over the content?

I've tried a mouse-enter / mouse-leave listener to change the alwaysShowTracks, but unfortunately the Scrollbar doesn't do anything with the value

**Comment by eltongonc** [comment]
This does the trick: 

(.SCSS)
```scss
.element {
 .scrollbar-track.show,
  .scrollbar-track:hover {
    opacity: 0;
    transition: 0.3s ease-in-out;
    background-color: ${({ theme }) => theme.main};

    .scrollbar-thumb {
      background-color: ${({ theme }) => theme.textColor};
    }
  }

  &:hover {
    .scrollbar-track.show,
    .scrollbar-track:hover {
      opacity: 1;
    }
  }
}
```
